# Docker Compose Example for inductiveautomation/ignition
# Compose Spec: https://github.com/compose-spec/compose-spec/blob/master/spec.md
---
services:
  # Ignition Gateway Spoke
  gateway-dev-spoke:
    image: inductiveautomation/ignition:8.1.28
    ports:
      - 9088:8088
    volumes:
      - ./modules/Batch-module.modl:/usr/local/bin/ignition/user-lib/modules/Batch-module.modl
      - ./modules/Document_Management-module.modl:/usr/local/bin/ignition/user-lib/modules/Document_Management-module.modl
      - ./modules/OEE_Downtime-module.modl:/usr/local/bin/ignition/user-lib/modules/OEE_Downtime-module.modl
      - ./modules/Production-module.modl:/usr/local/bin/ignition/user-lib/modules/Production-module.modl
    # env_file: ignition.env  # optionally specify variables in a file, or using `environment:` below
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=datauser
      - GATEWAY_ADMIN_PASSWORD=datauser
      - IGNITION_EDITION=standard
      - GATEWAY_MODULES_ENABLED=alarm-notification,allen-bradley-drivers,bacnet-driver,dnp3-driver,enterprise-administration,iec-61850-driver,logix-driver,modbus-driver-v2,omron-driver,opc-ua,perspective,reporting,serial-support-client,serial-support-gateway,sfc,siemens-drivers,sms-notification,sql-bridge,symbol-factory,tag-historian,udp-tcp-drivers,vision,voice-notification,web-browser,web-developer
      - TZ=America/New_York # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - GATEWAY_NETWORK_0_HOST=gateway-dev-hub

    command: >
      -n docker-dev-spoke -- gateway.resolveHostNames=true / COPY *.modl /usr/local/bin/ignition/user-lib/modules/

  gateway-dev-hub:
    image: inductiveautomation/ignition:8.1.28
    ports:
      - 9888:8088
    volumes:
      - ./modules/Batch-module.modl:/usr/local/bin/ignition/user-lib/modules/Batch-module.modl
      - ./modules/Document_Management-module.modl:/usr/local/bin/ignition/user-lib/modules/Document_Management-module.modl
      - ./modules/OEE_Downtime-module.modl:/usr/local/bin/ignition/user-lib/modules/OEE_Downtime-module.modl
      - ./modules/Production-module.modl:/usr/local/bin/ignition/user-lib/modules/Production-module.modl
      - ./modules/Sepasoft_Business_Connector-module.modl:/usr/local/bin/ignition/user-lib/modules/Sepasoft_Business_Connector-module.modl
      - ./modules/Web+Service-module.modl:/usr/local/bin/ignition/user-lib/modules/Web+Service-module.modl
    # env_file: ignition.env  # optionally specify variables in a file, or using `environment:` below
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=datauser
      - GATEWAY_ADMIN_PASSWORD=datauser
      - IGNITION_EDITION=standard
      - GATEWAY_MODULES_ENABLED=alarm-notification,allen-bradley-drivers,bacnet-driver,dnp3-driver,enterprise-administration,iec-61850-driver,logix-driver,modbus-driver-v2,omron-driver,opc-ua,perspective,reporting,serial-support-client,serial-support-gateway,sfc,siemens-drivers,sms-notification,sql-bridge,symbol-factory,tag-historian,udp-tcp-drivers,vision,voice-notification,web-browser,web-developer
      - TZ=America/New_York # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List

    command: >
      -n docker-dev-hub -- gateway.resolveHostNames=true docker cp foo.txt container_id:/foo.txt

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=yourStrong(!)Password"
    ports:
      - "1433:1433"
    hostname: mssql
    volumes:
      - "mssql-azuresql-edge-data:/var/opt/mssql"
volumes:
  mssql-azuresql-edge-data:
